CREATE TABLE USER_TBL
(
    USER_ID         VARCHAR2(20)    PRIMARY KEY,
    USER_PW         VARCHAR2(1000)    NOT NULL,
    USER_NAME       VARCHAR2(20)    NOT NULL,
    USER_BIRTH      VARCHAR2(50)    NOT NULL,
    USER_EMAIL      VARCHAR2(100)   NOT NULL,
    USER_PHONE      VARCHAR2(50)    NOT NULL,
    GENDER          VARCHAR2(6)     NOT NULL,
    USER_OADDRESS   VARCHAR2(50)    NOT NULL,
    USER_ADDRESS    VARCHAR2(200)   NOT NULL,
    USER_DTADDRESS  VARCHAR2(200)   NOT NULL,
    REGDATE         DATE            DEFAULT SYSDATE,
    NICKNAME        VARCHAR2(50)    UNIQUE,
    LOCA_PROV       VARCHAR2(10)
);

INSERT INTO USER_TBL(USER_ID, USER_PW, USER_NAME, USER_BIRTH, USER_EMAIL, USER_PHONE, GENDER, USER_OADDRESS, USER_ADDRESS, USER_DTADDRESS, NICKNAME)
VALUES( 'where', '1234', '홍길동', '19920424', 'greencom@naver.com', '0519121000', '남', '47296', '부산광역시 부산진구 중앙대로 688', '한준빌딩 4층 401호', '1');
commit;

-- 프로필사진
CREATE TABLE USER_FILE
(
    USER_IMG_NUM    NUMBER(5, 0)  NOT NULL
   , USER_ID    VARCHAR2(20)  NOT NULL
   , FILENAME   VARCHAR2(300) NOT NULL
   , FILEEXT    VARCHAR2(30)  NOT NULL
   , SFILENAME  VARCHAR2(300) NOT NULL
    CONSTRAINT FK_USER_ID FOREIGN KEY(USER_ID)
         REFERENCES USER_TBL(USER_ID) ON DELETE CASCADE
    
);

DROP TABLE USER_FILE;

CREATE SEQUENCE SEQ_USER_IMG_NUM
START WITH 1 
INCREMENT BY 1 
NOMAXVALUE NOCACHE; 
commit;